# Generated by Django 4.2.7 on 2023-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corner_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cornerimage',
            name='picture_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
