# Generated by Django 4.2.7 on 2023-11-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corner_ai', '0004_alter_cornerimage_picture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cornerimage',
            old_name='info',
            new_name='product_name',
        ),
    ]
